version: "3.1"

services:
  myjenkins:
    image: jenkins/jenkins:latest
    ports:
     - "8080:8080"
    volumes:
     - "./jobs:/var/jenkins_home/jobs/"
     - "./m2deps:/var/jenkins_home/.m2/repository/"


